<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TblBookingTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tbl_booking')->delete();
        
        \DB::table('tbl_booking')->insert(array (
            0 => 
            array (
                'bookingId' => 4,
                'tourId' => 2,
                'userId' => 9,
                'fullName' => 'Hoang Tran',
                'email' => 'minhhoangse6@gmail.com',
                'phoneNumber' => '0123456789',
                'address' => '123 Hai Ba Trung',
                'bookingDate' => '2025-03-20 20:52:29',
                'numAdults' => 1,
                'numChildren' => 0,
                'totalPrice' => 5990000.0,
                'bookingStatus' => 'y',
                'start_date' => NULL,
                'end_date' => NULL,
            ),
            1 => 
            array (
                'bookingId' => 5,
                'tourId' => 8,
                'userId' => 9,
                'fullName' => 'Hoang Tran',
                'email' => 'admin1@gmail.com',
                'phoneNumber' => '0123456789',
                'address' => '123 Hai Ba Trung',
                'bookingDate' => '2025-03-24 00:42:07',
                'numAdults' => 1,
                'numChildren' => 0,
                'totalPrice' => 669000.0,
                'bookingStatus' => 'f',
                'start_date' => NULL,
                'end_date' => NULL,
            ),
            2 => 
            array (
                'bookingId' => 6,
                'tourId' => 3,
                'userId' => 9,
                'fullName' => 'Hoang Tran',
                'email' => 'minhhoangse6@gmail.com',
                'phoneNumber' => '01234446456',
                'address' => '123 Hai Ba Trung',
                'bookingDate' => '2025-03-25 23:24:59',
                'numAdults' => 2,
                'numChildren' => 1,
                'totalPrice' => 11680000.0,
                'bookingStatus' => 'y',
                'start_date' => NULL,
                'end_date' => NULL,
            ),
            3 => 
            array (
                'bookingId' => 7,
                'tourId' => 9,
                'userId' => 12,
                'fullName' => 'Hoang Tran',
                'email' => 'minhhoangse6@gmail.com',
                'phoneNumber' => '0124345893',
                'address' => '123 Hai Ba Trung',
                'bookingDate' => '2025-03-25 23:26:17',
                'numAdults' => 2,
                'numChildren' => 1,
                'totalPrice' => 7970000.0,
                'bookingStatus' => 'f',
                'start_date' => NULL,
                'end_date' => NULL,
            ),
            4 => 
            array (
                'bookingId' => 8,
                'tourId' => 7,
                'userId' => 9,
                'fullName' => 'Hoang Tran',
                'email' => 'minhhoangse6@gmail.com',
                'phoneNumber' => '0124534553',
                'address' => '123 Hai Ba Trung',
                'bookingDate' => '2025-03-24 15:38:11',
                'numAdults' => 1,
                'numChildren' => 1,
                'totalPrice' => 7185000.0,
                'bookingStatus' => 'y',
                'start_date' => NULL,
                'end_date' => NULL,
            ),
            5 => 
            array (
                'bookingId' => 9,
                'tourId' => 7,
                'userId' => 12,
                'fullName' => 'Hoang Tran',
                'email' => 'minhhoangse6@gmail.com',
                'phoneNumber' => '01234565788',
                'address' => '123 Hai Ba Trung',
                'bookingDate' => '2025-03-24 15:38:05',
                'numAdults' => 2,
                'numChildren' => 2,
                'totalPrice' => 14370000.0,
                'bookingStatus' => 'y',
                'start_date' => NULL,
                'end_date' => NULL,
            ),
            6 => 
            array (
                'bookingId' => 10,
                'tourId' => 6,
                'userId' => 12,
                'fullName' => 'Hoang Tran',
                'email' => 'minhhoangse6@gmail.com',
                'phoneNumber' => '01234567896',
                'address' => '123 Hai Ba Trung',
                'bookingDate' => '2025-03-25 17:20:30',
                'numAdults' => 2,
                'numChildren' => 0,
                'totalPrice' => 6580000.0,
                'bookingStatus' => 'f',
                'start_date' => NULL,
                'end_date' => NULL,
            ),
            7 => 
            array (
                'bookingId' => 11,
                'tourId' => 2,
                'userId' => 12,
                'fullName' => 'Hoang Tran',
                'email' => 'minhhoangse6@gmail.com',
                'phoneNumber' => '1244235388',
                'address' => '123 Hai Ba Trung',
                'bookingDate' => '2025-03-26 00:08:49',
                'numAdults' => 2,
                'numChildren' => 1,
                'totalPrice' => 16175000.0,
                'bookingStatus' => 'c',
                'start_date' => NULL,
                'end_date' => NULL,
            ),
            8 => 
            array (
                'bookingId' => 12,
                'tourId' => 4,
                'userId' => 12,
                'fullName' => 'Hoang Tran',
                'email' => 'minhhoangse6@gmail.com',
                'phoneNumber' => '1234567890',
                'address' => '123 Hai Ba Trung',
                'bookingDate' => '2025-03-26 18:45:10',
                'numAdults' => 2,
                'numChildren' => 3,
                'totalPrice' => 16950000.0,
                'bookingStatus' => 'y',
                'start_date' => NULL,
                'end_date' => NULL,
            ),
            9 => 
            array (
                'bookingId' => 13,
                'tourId' => 1,
                'userId' => 12,
                'fullName' => 'Hoang Tran',
                'email' => 'minhhoangse6@gmail.com',
                'phoneNumber' => '1234567890',
                'address' => '123 Hai Ba Trung',
                'bookingDate' => '2025-04-02 23:33:41',
                'numAdults' => 2,
                'numChildren' => 2,
                'totalPrice' => 15020000.0,
                'bookingStatus' => 'f',
                'start_date' => NULL,
                'end_date' => NULL,
            ),
            10 => 
            array (
                'bookingId' => 14,
                'tourId' => 1,
                'userId' => 12,
                'fullName' => 'Hoang Tran 1',
                'email' => 'minhhoangse6@gmail.com',
                'phoneNumber' => '12312312312',
                'address' => '123 Hai Ba Trung',
                'bookingDate' => '2025-04-15 21:19:43',
                'numAdults' => 2,
                'numChildren' => 1,
                'totalPrice' => 11800000.0,
                'bookingStatus' => 'y',
                'start_date' => '2025-04-02',
                'end_date' => '2025-04-05',
            ),
            11 => 
            array (
                'bookingId' => 15,
                'tourId' => 1,
                'userId' => 12,
                'fullName' => 'Hoang Tran',
                'email' => 'minhhoangse6@gmail.com',
                'phoneNumber' => '1321231246',
                'address' => '123 Hai Ba Trung',
                'bookingDate' => '2025-04-03 00:09:16',
                'numAdults' => 2,
                'numChildren' => 0,
                'totalPrice' => 8580000.0,
                'bookingStatus' => 'c',
                'start_date' => '2025-04-03',
                'end_date' => '2025-04-06',
            ),
            12 => 
            array (
                'bookingId' => 16,
                'tourId' => 1,
                'userId' => 12,
                'fullName' => 'Hoang Tran',
                'email' => 'minhhoangse6@gmail.com',
                'phoneNumber' => '1231231231',
                'address' => '123 Hai Ba Trung',
                'bookingDate' => '2025-04-15 21:19:42',
                'numAdults' => 2,
                'numChildren' => 0,
                'totalPrice' => 8580000.0,
                'bookingStatus' => 'y',
                'start_date' => '2025-04-03',
                'end_date' => '2025-04-06',
            ),
            13 => 
            array (
                'bookingId' => 17,
                'tourId' => 1,
                'userId' => 12,
                'fullName' => 'Hoang Tran',
                'email' => 'minhhoangse6@gmail.com',
                'phoneNumber' => '1234561235',
                'address' => '123 Hai Ba Trung',
                'bookingDate' => '2025-04-15 21:19:39',
                'numAdults' => 2,
                'numChildren' => 1,
                'totalPrice' => 11800000.0,
                'bookingStatus' => 'y',
                'start_date' => '2025-04-03',
                'end_date' => '2025-04-06',
            ),
            14 => 
            array (
                'bookingId' => 18,
                'tourId' => 1,
                'userId' => 12,
                'fullName' => 'Hoang Tran 2',
                'email' => 'minhhoangse6@gmail.com',
                'phoneNumber' => '1231231231',
                'address' => '123 Hai Ba Trung',
                'bookingDate' => '2025-04-03 12:57:16',
                'numAdults' => 2,
                'numChildren' => 1,
                'totalPrice' => 11800000.0,
                'bookingStatus' => 'c',
                'start_date' => '2025-04-16',
                'end_date' => '2025-04-19',
            ),
            15 => 
            array (
                'bookingId' => 19,
                'tourId' => 1,
                'userId' => 12,
                'fullName' => 'Hoang Tran',
                'email' => 'minhhoangse6@gmail.com',
                'phoneNumber' => '1231231231',
                'address' => '123 Hai Ba Trung',
                'bookingDate' => '2025-04-03 12:59:39',
                'numAdults' => 2,
                'numChildren' => 1,
                'totalPrice' => 11800000.0,
                'bookingStatus' => 'c',
                'start_date' => '2025-04-16',
                'end_date' => '2025-04-19',
            ),
            16 => 
            array (
                'bookingId' => 20,
                'tourId' => 1,
                'userId' => 12,
                'fullName' => 'Hoang Tran',
                'email' => 'minhhoangse6@gmail.com',
                'phoneNumber' => '1231231231',
                'address' => '123 Hai Ba Trung',
                'bookingDate' => '2025-04-03 13:03:59',
                'numAdults' => 1,
                'numChildren' => 1,
                'totalPrice' => 7510000.0,
                'bookingStatus' => 'c',
                'start_date' => '2025-04-19',
                'end_date' => '2025-04-22',
            ),
            17 => 
            array (
                'bookingId' => 21,
                'tourId' => 1,
                'userId' => 12,
                'fullName' => 'Hoang Tran',
                'email' => 'minhhoangse6@gmail.com',
                'phoneNumber' => '1231231231',
                'address' => '123 Hai Ba Trung',
                'bookingDate' => '2025-04-03 13:24:57',
                'numAdults' => 1,
                'numChildren' => 1,
                'totalPrice' => 7510000.0,
                'bookingStatus' => 'y',
                'start_date' => '2025-04-03',
                'end_date' => '2025-04-06',
            ),
            18 => 
            array (
                'bookingId' => 22,
                'tourId' => 1,
                'userId' => 12,
                'fullName' => 'Hoang Tran',
                'email' => 'minhhoangse6@gmail.com',
                'phoneNumber' => '1234567890',
                'address' => '123 Hai Ba Trung',
                'bookingDate' => '2025-04-15 21:19:39',
                'numAdults' => 1,
                'numChildren' => 2,
                'totalPrice' => 10730000.0,
                'bookingStatus' => 'y',
                'start_date' => '2025-04-15',
                'end_date' => '2025-04-18',
            ),
            19 => 
            array (
                'bookingId' => 23,
                'tourId' => 4,
                'userId' => 12,
                'fullName' => 'Hoang Tran',
                'email' => 'minhhoangse6@gmail.com',
                'phoneNumber' => '1234568764',
                'address' => '123 Hai Ba Trung',
                'bookingDate' => '2025-04-15 21:19:37',
                'numAdults' => 2,
                'numChildren' => 0,
                'totalPrice' => 7980000.0,
                'bookingStatus' => 'y',
                'start_date' => '2025-04-16',
                'end_date' => '2025-04-20',
            ),
            20 => 
            array (
                'bookingId' => 24,
                'tourId' => 10,
                'userId' => 12,
                'fullName' => 'Hoang Tran',
                'email' => 'minhhoangse6@gmail.com',
                'phoneNumber' => '12345467886',
                'address' => '123 Hai Ba Trung',
                'bookingDate' => '2025-04-22 16:18:41',
                'numAdults' => 2,
                'numChildren' => 1,
                'totalPrice' => 7970000.0,
                'bookingStatus' => 'y',
                'start_date' => '2025-04-23',
                'end_date' => '2025-04-25',
            ),
            21 => 
            array (
                'bookingId' => 25,
                'tourId' => 11,
                'userId' => 12,
                'fullName' => 'Hoang Tran',
                'email' => 'minhhoangse6@gmail.com',
                'phoneNumber' => '1234567890',
                'address' => '123 Hai Ba Trung',
                'bookingDate' => '2025-04-22 16:48:37',
                'numAdults' => 1,
                'numChildren' => 0,
                'totalPrice' => 1200000.0,
                'bookingStatus' => 'y',
                'start_date' => '2025-04-22',
                'end_date' => '2025-04-23',
            ),
            22 => 
            array (
                'bookingId' => 26,
                'tourId' => 27,
                'userId' => 12,
                'fullName' => 'Hoang Tran',
                'email' => 'minhhoangse6@gmail.com',
                'phoneNumber' => '1234567890',
                'address' => '123 Hai Ba Trung',
                'bookingDate' => '2025-04-23 17:06:24',
                'numAdults' => 2,
                'numChildren' => 1,
                'totalPrice' => 17500000.0,
                'bookingStatus' => 'y',
                'start_date' => '2025-05-03',
                'end_date' => '2025-04-26',
            ),
            23 => 
            array (
                'bookingId' => 27,
                'tourId' => 27,
                'userId' => 12,
                'fullName' => 'Hoang Tran',
                'email' => 'minhhoangse6@gmail.com',
                'phoneNumber' => '1234567890',
                'address' => '123 Hai Ba Trung',
                'bookingDate' => '2025-04-24 17:15:44',
                'numAdults' => 3,
                'numChildren' => 2,
                'totalPrice' => 29000000.0,
                'bookingStatus' => 'y',
                'start_date' => '2025-04-24',
                'end_date' => '2025-04-27',
            ),
        ));
        
        
    }
}